### ISSUE TITLE
Is it possible to use UserSecrets in this sample?

### ISSUE THREAD

**Issue by Titowisk** [LXBdev/WebJob-netcore-sample#1]
Hi LXBdev, do you know how to use secrets.json with webjobs sdk in netcore 3.1 ?

**Comment by LXBdev** [comment]
Should work without issues, added an example here: https://github.com/LXBdev/WebJob-netcore-sample/commit/70606fccb0f6a28f7f1b3088191b6f0b2eaefd23

**Comment by Titowisk** [comment]
**Thanks for helping**. I tried to do that in my webjob but it didn't work. The function tries to find a `AzureWebJobsStorage` key in my `appsettings.json` instead of my `secrets.json` for some reason.

**Comment by LXBdev** [comment]
It works fine for me. Make sure you have the correct structure in your `secrets.json`.

```
{
  "ConnectionStrings": {
    "AzureWebJobsStorage": "..."
  }
}
```

Edit: You can also check if `context.HostingEnvironment.IsDevelopment()` is `true`, e.g. by using a debugger.

You launch.json can look like this:

```
{
  "profiles": {
    "WebJob-netcore-sample": {
      "commandName": "Project",
      "environmentVariables": {
        "DOTNET_ENVIRONMENT": "Development"
      }
    }
  }
}
```

**Comment by Titowisk** [comment]
Oh my god. You are right!! I did what you said and it worked fine!

Do you want to give that answear in my [stackoverflow question](https://stackoverflow.com/questions/63715422/i-am-having-trouble-in-using-user-secrets-with-azure-sdk-webjobs-in-a-console-ap/63721103?noredirect=1#comment112828106_63721103)  so that I can give you credit for helping me ?

**Comment by LXBdev** [comment]
Glad I could help :)
